-- 2단계: 공개 data.json의 가상 자료를 학습용 테이블로 이전
-- 실제 비밀값이나 실제 학생 자료를 포함하지 않습니다.

create table if not exists public.learning_notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null
);

-- owner_id는 향후 인증 연계를 위한 자리만 마련하며 auth.users와 연결하지 않습니다.
alter table public.learning_notes enable row level security;

-- anon/authenticated에는 자료 읽기 권한을 주지 않습니다.
revoke all on table public.learning_notes from anon, authenticated;
revoke all on sequence public.learning_notes_id_seq from anon, authenticated;

-- 현재 data.json에 있던 가상 메모 네 건을 학습용 데이터로 이전합니다.
insert into public.learning_notes (owner_id, title, content)
values
  (null, '과제', '실습용 가상 과제 기록'),
  (null, '포트폴리오', '실습용 가상 포트폴리오 기록'),
  (null, '아침 리추얼', '실습용 가상 리추얼 기록'),
  (null, '훈련 행정 자료', '실습용 가상 행정 기록');
